services:
  packing-api:
    image: packing-app
    build:
      context: .
      dockerfile: Packing/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development